"""empty message

Revision ID: a781ee5e9f9d
Revises: 762402052503
Create Date: 2021-04-03 19:09:15.144959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a781ee5e9f9d'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('location', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=25), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['phone'])
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'salt')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'location')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
